type PaginationMeta = {
  pagination: {
    page: number;
    pageSize: number;
    pageCount: number;
    total: number;
  };
};

export type ApiResponse<T> = {
  data: T;
  meta: PaginationMeta;
};

export type StrapiEntry = {
  id: number;
  documentId: string;
};

/** One responsive derivative generated by Strapi's upload plugin. */
export type StrapiMediaFormat = {
  url: string;
  width: number;
  height: number;
  size?: number;
};

export type StrapiMediaFormats = {
  thumbnail?: StrapiMediaFormat;
  small?: StrapiMediaFormat;
  medium?: StrapiMediaFormat;
  large?: StrapiMediaFormat;
};

export type StrapiMediaSize = keyof StrapiMediaFormats;

export type StrapiMedia = StrapiEntry & {
  url: string;
  alternativeText?: string | null;
  width?: number | null;
  height?: number | null;
  formats?: StrapiMediaFormats | null;
};
